<#-- Import utility functions -->
<#include "utils/functions.ftl">

<#-- Include header with package declaration and imports -->
<#include "fragments/header.ftl">

/**
* GENERATED BY MAVEN-GRAPHQL-JAVA-CODEGEN-PLUGIN.
*/
public class ${className} {

public static class Schema {

}

public static class Types {
<#-- Include enum types -->
<#include "types/enum.ftl">

<#-- Include object types -->
<#include "types/object.ftl">

<#-- Include object fragment types -->
<#include "types/object_fragment.ftl">

<#-- Include list type fragment types -->
<#include "types/list_type_fragments.ftl">

<#-- Include scalar fragment types -->
<#include "types/scalar_fragment.ftl">

<#-- Include input object types -->
<#include "types/input_object.ftl">
}

<#-- Include query and mutation operations -->
<#include "operations/query_mutation.ftl">

<#-- Include GraphQL Builders content -->
${gqlBuildersContent}

}
